name: Docker Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: # Add this
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        target: production
        build-args: |
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          PORT=${{ secrets.PORT }}
        tags: ghcr.io/${{ github.repository }}:latest
    
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ghcr.io/${{ github.repository }}:latest
          docker stop teklifaz || true
          docker rm teklifaz || true
          docker run -d \
            --name teklifaz \
            -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            -e PORT="${{ secrets.PORT }}" \
            -p 127.0.0.1:${{ secrets.PORT }}:${{ secrets.PORT }} \
            ghcr.io/${{ github.repository }}:latest